### ISSUE TITLE
Usage of single quotes in HTML

### ISSUE THREAD

**Issue by rawrin** [caarbon/node-conventions#4]
We're using single quotes everywhere else, but in HTML or JSX it seems common to use double quotes. I prefer single quotes in this instance for the sake of uniformity, but I'm not married to the idea and I'm willing to change as long as we do sweeping change to all HTML/JSX on the board to use double quotes. Thoughts?

cc @boichee, @tmarshall

**Comment by tmarshall** [comment]
I feel that this is not the right repo for HTML conventions. Though JSX makes sense, since it's in the JS domain.

I agree with single quotes. We already enforce that with JSHint. We should go through all our lint restrictions and make sure they are documented in this repo.

And it seems like this repo should change from `node conventions` to `javascript conventions`, with node-specific conventions stated as so.

**Comment by boichee** [comment]
( @rawrin @tmarshall ): I personally prefer double quotes in HTML and thus, I'd rather see double quotes in JSX as well. 

#### HTML: Single or Double Quotes?

The W3C standard for HTML [allows for single or double quotes](http://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.2) around attribute values:

> By default, SGML requires that all attribute values be delimited using either double quotation marks (ASCII decimal 34) or single quotation marks (ASCII decimal 39). Single quote marks can be included within the attribute value when the value is delimited by double quote marks, and vice versa. 

##### My personal standard has always been to use double quotes around attr values:

I prefer this, because it's more common to use single quotes around strings in Javascript. By using double quotes in HTML/XML you can preserve this standard if you have to embed Javascript in an HTML attribute — like a click handler:

``` html
<div id="my-link">
  <a href="#" onclick="fnWithStringAsParam('This is a string')">Click here to do something!</a>
</div>
```

So, I'm happy to use single quotes in Javascript, but would very much prefer that we standardize JSX to use double quotes around attributes.

**Comment by tmarshall** [comment]
That's a good point for double quotes in html

**Comment by caamuerte** [comment]
@rawrin :heart: :skull:

> Death is no more than passing from one room into another. But there's a difference for me, you know. Because in that other room I shall be able to see.
> 
> _\- Helen Keller_

**Comment by caamuerte** [comment]
@rawrin :heart: :skull:

> The day which we fear as our last is but the birthday of eternity.
> 
> _\- Lucius Annaeus Seneca_
